# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-drv-vesa

# >> macros
# << macros

Summary:    Xorg X11 vesa video driver
Version:    2.3.2
Release:    1
Group:      System/X11 Hardware Support
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/archive/individual/driver/xf86-video-vesa-%{version}.tar.bz2
Source100:  xorg-x11-drv-vesa.yaml
Patch0:     vesa.patch
Patch1:     vesa-nodga.patch
Requires:   xorg-x11-server-Xorg
BuildRequires:  pkgconfig(xorg-macros) >= 1.8
BuildRequires:  pkgconfig(xorg-server) >= 1.0.99.901
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(fontsproto)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(renderproto)
BuildRequires:  pkgconfig(xextproto)

%description
%{summary}.



%prep
%setup -q -n xf86-video-vesa-%{version}

# vesa.patch
%patch0 -p1
# vesa-nodga.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/drivers/vesa_drv.so
%doc %{_mandir}/man4/vesa.4*
# << files
