# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# On 2010-02-20 09:46:05
# 
# >> macros
# << macros

Name:       xorg-x11-drv-vesa
Summary:    Xorg X11 vesa video driver
Version:    2.3.0
Release:    1
Group:      User Interface/X Hardware Support
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/archive/individual/driver/xf86-video-vesa-%{version}.tar.bz2
Source100: xorg-x11-drv-vesa.yaml
Patch0:     vesa.patch
Patch1:     vesa-nodga.patch
Requires:   xorg-x11-server-Xorg
BuildRequires:  pkgconfig(xorg-server) >= 1.0.99.901
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(fontsproto)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(renderproto)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(inputproto)

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Description: %{summary}



%prep
%setup -q -n xf86-video-vesa-%{version}
%patch0 -p1
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post


%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post
%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/drivers/vesa_drv.so
%doc %{_mandir}/man4/vesa.4*
# << files


